name: GitHub Artifacts

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip debian.zip www/
      - run: gh release create v$( date +%Y%m%d ) debian.zip
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
