name: GitHub Artifacts

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: www
