name: GitHub Artifacts

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip debian.zip www/
      - run: gh release create v0.0.1 debian.zip
