name: GitHub Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip debian.zip www/
      - run: gh release create  echo v$( date +%Y%m%d ) debian.zip
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
