name: GitHub Artifacts

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
  schedule:
    - cron: '15 10 * * *'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Zip debian files
        run: zip debian.zip www/
      
      - name: Create release
        run: gh release create v$( date +%Y%m%d ) debian.zip
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
